services:
  mailer:
    image: rust:1.85-alpine
    container_name: rust-server
    env_file:
      - .env
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "apk add --no-cache musl-dev pkgconfig openssl-dev openssl-libs-static && cargo build --release && ./target/release/rust-app"
    ports:
      - "8080:8080"
