services:
  mailer:
    image: rust:1.85-alpine
    container_name: rust-server
    env_file:
      - .env
    volumes:
      - /var/www/html/efg/backend/:/app
    working_dir: /app
    command: sh -c "apk add --no-cache musl-dev pkgconfig openssl-dev openssl-libs-static && cargo build --release && ./target/release/rust-app"
    expose:
      - "8080"
    networks:
      - web-network

  nginx:
    image: nginx:alpine
    container_name: nginx-ssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      -  /var/www/html/:/usr/share/nginx/html/
      - ./validation/:/usr/share/nginx/certification/.well-known/pki-validation/
      - ./ssl/:/etc/ssl/
    restart: always
    networks:
      - web-network

networks:
  web-network:
    driver: bridge