name: Deploy para GCP via gcloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Criar secret.json
        run: |
          cat <<EOF > secret.json
          {
            "email": {
              "service_id": "${{ secrets.SERVICE_ID }}",
              "template_id": "${{ secrets.TEMPLATE_ID }}",
              "public_key": "${{ secrets.PUBLIC_KEY }}",
              "to_email": "uzeda.dev@gmail.com"
            },
            "turmas": {
              "estatistica": { "senha": "${{ secrets.SENHA_EST }}" },
              "terceirao": { "senha": "${{ secrets.SENHA_TERCEIRAO }}" },
              "logica": { "senha": "${{ secrets.SENHA_LOGICA }}" }
            }
          }
          EOF

      - name: Listar arquivos no diretório
        run: ls -la ./

      - name: Configurar ambiente Node.js e criar package.json
        run: |
          echo "Instalando Node.js, Marp CLI e Mermaid CLI..."
          sudo apt-get update -y
          sudo apt-get install -y nodejs npm 
          cat <<EOF > package.json
          {
            "name": "marp-converter",
            "version": "1.0.0",
            "description": "Marp conversion script",
            "dependencies": {
              "@marp-team/marp-cli": "^3.4.0",
              "@marp-team/marpit": "^2.6.2",
              "markdown-it-attrs": "^4.1.6",
              "markdown-it-container": "^4.0.0",
              "markdown-it-deflist": "^3.0.0",
              "markdown-it-footnote": "^4.0.0",
              "markdown-it-mathjax3": "^4.3.2",
              "markdown-it-mermaid": "^0.2.5"
            }
          }
          EOF

      - name: Instalar dependências do Node.js
        run: npm install

      - name: Converter Markdown para slides HTML com Marp
        run: |
          echo "Convertendo todos os arquivos .md recursivamente em HTML..."
          find ./turmas -type f -name "*.md" -print0 | xargs -0 -n1 -I{} sh -c '
            mdfile="{}"
            outfile="${mdfile%.md}.html"
            echo "Convertendo $mdfile -> $outfile"
            ./node_modules/.bin/marp "$mdfile" --engine ./engine.js -o "$outfile"
          '
        shell: bash

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Testar conexão com a VM
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="echo Conexão bem-sucedida"
            
      - name: Copiar arquivos para a VM (para /tmp)
        run: |
          gcloud compute scp --recurse ./* \
            ${{ secrets.GCP_INSTANCE_NAME }}:/tmp/deploy \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Mover arquivos para /var/www/html/efg
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="sudo cp -r /tmp/deploy/* /var/www/html/efg/"
