name: Deploy para GCP via gcloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Criar secret.json
        run: |
          cat <<EOF > secret.json
          {
            "email": {
              "service_id": "${{ secrets.SERVICE_ID }}",
              "template_id": "${{ secrets.TEMPLATE_ID }}",
              "public_key": "${{ secrets.PUBLIC_KEY }}",
              "to_email": "uzeda.dev@gmail.com"
            },
            "turmas": {
              "estatistica": { "senha": "${{ secrets.SENHA_EST }}" },
              "terceirao": { "senha": "${{ secrets.SENHA_TERCEIRAO }}" }
            }
          }
          EOF

      - name: Listar arquivos no diretório
        run: ls -la ./

      # ---------- 1. Compilar com Marp ----------
      - name: Instalar Node.js e Marp CLI
        run: |
          echo "Instalando Node.js e Marp CLI..."
          sudo apt-get update -y
          sudo apt-get install -y nodejs npm
          sudo npm install -g @marp-team/marp-cli

      - name: Converter Markdown para slides HTML com Marp
        run: |
           echo "Convertendo arquivos .md em ./ para slides HTML"
           marp --input-dir ./ --html
        shell: bash

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Testar conexão com a VM
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="echo Conexão bem-sucedida"
            
      - name: Copiar arquivos para a VM (para /tmp)
        run: |
          gcloud compute scp --recurse ./* \
            ${{ secrets.GCP_INSTANCE_NAME }}:/tmp/deploy \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Mover arquivos para /var/www/html/efg
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="sudo cp -r /tmp/deploy/* /var/www/html/efg/"
